apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  aws-region: {{ .Values.global.awsRegion | quote }}
  s3-bucket: {{ .Values.aws.s3Bucket | quote }}
  client-urls: {{ .Values.clientUrls | quote }}
  streaming-public-url: {{ .Values.streamingPublicUrl | quote }}
