apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.auth.name }}
            port:
              number: {{ .Values.services.auth.port }}
      - path: /api/streaming
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.streaming.name }}
            port:
              number: {{ .Values.services.streaming.port }}
      - path: /api/admin
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.admin.name }}
            port:
              number: {{ .Values.services.admin.port }}
      - path: /api/chat
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.services.chat.name }}
            port:
              number: {{ .Values.services.chat.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.port }}
